# From here: https://github.com/reviewdog/action-misspell
name: reviewdog misspell
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@master
        with:
          github_token: ${{ secrets.github_token }}
          locale: "UK"
          reporter: github-pr-check # Available: github-pr-check shows a stop icon instead of checkmark
          level: info
